
`define S_WIDTH 3
`define X_COORD_WIDTH 8
`define Y_COORD_WIDTH 7
`define COLOUR_WIDTH   3
`define DELAY_WIDTH   32

`define INSTRUCTION_WIDTH   32
`define RESULT_WIDTH   32

`define SCREEN_WIDTH  `X_COORD_WIDTH'd160
`define SCREEN_HEIGHT `Y_COORD_WIDTH'd120

`define ANT_WIDTH  `X_COORD_WIDTH'd3
`define ANT_HEIGHT `Y_COORD_WIDTH'd3

`define OPCODE_WIDTH 4
`define OPCODE_NULL     `OPCODE_WIDTH'd0
`define OPCODE_DRAW     `OPCODE_WIDTH'd1
`define OPCODE_MEMREAD  `OPCODE_WIDTH'd2
`define OPCODE_MEMWRITE `OPCODE_WIDTH'd3
`define OPCODE_DISPLAY  `OPCODE_WIDTH'd4

`define MEM_ADDR_WIDTH 16
`define MEM_DATA_WIDTH 12

`define FB_ADDR_WIDTH 15
`define FB_DATA_WIDTH `COLOUR_WIDTH

`define FITNESS_WIDTH 12

`define COLOUR_BG     `COLOUR_WIDTH'b111
`define COLOUR_ANT    `COLOUR_WIDTH'b000
`define COLOUR_FOOD   `COLOUR_WIDTH'b010
`define COLOUR_POISON `COLOUR_WIDTH'b100

`define NUM_ANT    `MEM_ADDR_WIDTH'd1
`define NUM_FOOD   `MEM_ADDR_WIDTH'd1
`define NUM_POISON `MEM_ADDR_WIDTH'd2

`define RAND_WIDTH 16

// TODO make sure the output with must be MEM_ADDR_WIDTH.
`define ADDR_FOOD_X(ID)           (ID)
`define ADDR_FOOD_Y(ID)           (ID + `NUM_FOOD)
`define ADDR_POISON_X(ID)         (ID + `MEM_ADDR_WIDTH'd2 * `NUM_FOOD)
`define ADDR_POISON_Y(ID)         (ID + `MEM_ADDR_WIDTH'd2 * `NUM_FOOD + `NUM_POISON)
`define ADDR_ANT_X(ID)            (ID + `MEM_ADDR_WIDTH'd2 * `NUM_FOOD + `MEM_ADDR_WIDTH'd2 * `NUM_POISON)
`define ADDR_ANT_Y(ID)            (ID + `MEM_ADDR_WIDTH'd2 * `NUM_FOOD + `MEM_ADDR_WIDTH'd2 * `NUM_POISON + `NUM_ANT)
`define ADDR_ANT_FITNESS(ID)      (ID + `MEM_ADDR_WIDTH'd2 * `NUM_FOOD + `MEM_ADDR_WIDTH'd2 * `NUM_POISON + `MEM_ADDR_WIDTH'd2 * `NUM_ANT)
