
`define OP_CODE_WIDTH 2
`define S_WIDTH 3
`define X_COORD_WIDTH 8
`define Y_COORD_WIDTH 7
`define COLOUR_WIDTH   3
`define DELAY_WIDTH   20

`define INSTRUCTION_WIDTH   32
`define RESULT_WIDTH   32

`define SCREEN_WIDTH  `X_COORD_WIDTH'd160
`define SCREEN_HEIGHT `Y_COORD_WIDTH'd120
